GET http://localhost:3001/api/v1
Accept: application/json

###

GET http://localhost:3003/api/v1/topGainers24Hours
Accept: application/json


###
GET http://localhost:3003/api/v1/topCoins
Accept: application/json

###

GET https://min-api.cryptocompare.com/data/all/coinlist
Apikey: {{cryptoCompare}}

###
GET https://api.binance.com/api/v3/ticker/24hr


###
GET http://localhost:3003/api/v1/getCandles
Accept: application/json

###
GET http://localhost:3003/api/v1/getExchangeInfo
Accept: application/json

###
GET http://localhost:3003/api/v1/getCryptoNews
Accept: application/json

###
GET http://localhost:3003/api/v1/getNewsDescription?id=18054530&url=https://cryptopanic.com/news/18054530/Litecoin-LTC-Price-Analysis-Bulls-Continue-to-Struggle-Near-100
Accept: application/json

###
GET http://localhost:3003/api/v1/getCryptoNewsDescription?id=18062410&url=https://cryptopanic.com/news/18062410/Robert-Kennedy-Jr-Government-Could-Ban-Seize-Bitcoin-CBDCs-Could-Lead-to-Financial-Slavery-Political-Tyranny
Accept: application/json