GET http://localhost:3001/api/v1
Accept: application/json

###

GET http://localhost:3003/api/v1/topGainers24Hours
Accept: application/json


###
GET http://localhost:3003/api/v1/topCoins
Accept: application/json

###

GET https://min-api.cryptocompare.com/data/all/coinlist
Apikey: {{cryptoCompare}}

###
GET https://api.binance.com/api/v3/ticker/24hr


###
GET http://localhost:3003/api/v1/getCandles
Accept: application/json
